### ISSUE TITLE
Ghosting external record

### ISSUE THREAD

**Issue by alexfelmeister** [chop-dbhi/biorepo-portal#108]
@seg1129 I have a record that is jumping between subject records then is showing up under two subjects in ETL. It comes and goes and also produces and error:

URL Redacted. 
'''
Environment:

Request Method: GET
Request URL: <redacted>

Django Version: 1.9.13
Python Version: 3.5.1
Installed Applications:
['django.contrib.admin',
 'django.contrib.auth',
 'django.contrib.contenttypes',
 'django.contrib.sessions',
 'django.contrib.sites',
 'django.contrib.messages',
 'django.contrib.staticfiles',
 'django.contrib.flatpages',
 'markdown_deux',
 'rest_framework.authtoken',
 'rest_framework',
 'registration',
 'session_security',
 'accounts',
 'brp',
 'api',
 'dataentry']
Installed Middleware:
['django.middleware.security.SecurityMiddleware',
 'django.contrib.sessions.middleware.SessionMiddleware',
 'django.middleware.common.CommonMiddleware',
 'django.middleware.csrf.CsrfViewMiddleware',
 'django.contrib.auth.middleware.AuthenticationMiddleware',
 'brp.middleware.LoggingMiddleware',
 'brp.middleware.MaintenanceMiddleware',
 'django.contrib.auth.middleware.SessionAuthenticationMiddleware',
 'session_security.middleware.SessionSecurityMiddleware',
 'dataentry.middleware.CheckPdsCredentialsMiddleware',
 'django.contrib.messages.middleware.MessageMiddleware',
 'django.middleware.clickjacking.XFrameOptionsMiddleware',
 'accounts.middleware.CheckEulaMiddleware']

Traceback:

File "/usr/lib/python3.5/site-packages/django/core/handlers/base.py" in get_response
  149.                     response = self.process_exception_by_middleware(e, request)

File "/usr/lib/python3.5/site-packages/django/core/handlers/base.py" in get_response
  147.                     response = wrapped_callback(request, *callback_args, **callback_kwargs)

File "/usr/lib/python3.5/site-packages/django/contrib/auth/decorators.py" in _wrapped_view
  23.                 return view_func(request, *args, **kwargs)

File "/usr/lib/python3.5/site-packages/django/views/generic/base.py" in view
  68.             return self.dispatch(request, *args, **kwargs)

File "/usr/lib/python3.5/site-packages/django/views/generic/base.py" in dispatch
  88.         return handler(request, *args, **kwargs)

File "/usr/lib/python3.5/site-packages/django/views/generic/base.py" in get
  157.         context = self.get_context_data(**kwargs)

File "/opt/app/dataentry/views/pds.py" in get_context_data
  50.             context['record'].record_id,

Exception Type: <redacted>
Exception Value: 'NoneType' object has no attribute 'record_id'
'''

**Comment by r3m0chop** [comment]
For what it's worth, it appears that the last successful CBTTC ETL would have been "5 days 10 hr ago" (according to Jenkin's nightly ETL attempts), so if this is not specific to the data itself, this error could be due to a change that went live in the last 4-5 days?

**Comment by seg1129** [comment]
issue resolved Temporarily. This issue was caused by an external record being deleted and then added again. The resolution was to update the caching for the given protocol which fixed the UI and ETL process. A permanent solution for this should include removing caching from ETL process and updating caching nightly.

**Comment by seg1129** [comment]
@alexanderkgonzalez can you remove caching links from the ETL process?

**Comment by seg1129** [comment]
A job has been created to re-cache data nightly

**Comment by seg1129** [comment]
We decided not to remove the process of grabbing BRP data from the BRP Cache in the nightly ETL process. There were many additional features added to the ETL since it was modified to pull data from the cache that rely on the cache formatting and making changes to this will take a large refactoring of the current stable working ETL. 

The job to re-cache subjects nightly has remediated this issue.
