### ISSUE TITLE
admin feature: update user nautilus credentials

### ISSUE THREAD

**Issue by seg1129** [chop-dbhi/biorepo-portal#148]
If a user is aligned with multiple protocols, when their nautilus credentials need to be updated, a BRP administrator needs to update each instance of their nautilus credentials. We need to simplify this process to input nautilus credentials for a single user once, and all instances of that user's nautilus credentials will all be updated at once.

**Comment by njackson2012** [comment]
I'm on it!

**Comment by alexanderkgonzalez** [comment]
@njackson2012

**Comment by njackson2012** [comment]
----------------------------------------
|     Nautilus API Key Update Feature    |
|         Requirements Document          |
|                                        |
|            Nick Jackson                |
|             April 17th                 |
|   					 |
 ----------------------------------------

Purpose:
	Admin user of the BRP need a better way to update their Nautilus credentials. As of right now they have to go to each of their individual Nautilus projects and manually update them. I am going to create a form which allows them to update all at once.

Requirements:

1. Users will see each project that will be altered listed.

2. Users will input the new key in a data field.

3. Once written, users can send the new password to be written instantly to each project with a single button press.

4. Once submitted, the user will be given an indication of both submission processing and success/failure.

5. If failure, the user will be told what went wrong and what is required to fix the problem.

**Comment by njackson2012** [comment]
We added two additional requirements to this issue:

6. The feature should not change user credentials which have empty password fields.

7. The feature should not change user credentials which have mismatched a data_source_username and assigned user's username. Additionally, these instances should be reported to the person trying to make the change so that they can more easily fix the situation.
