### ISSUE TITLE
Create unit-testing-specific setup instructions

### ISSUE THREAD

**Issue by aaron0browne** [chop-dbhi/biorepo-portal#177]
Local setup guide for the BRP toolkit is awesome and super comprehensive, but I think it might also be useful to have a short section of the README that lays out the minimum number of steps necessary to run the unit tests with `manage.py test`. Does that make sense? They're fresh in my mind so I'd be happy to write them down.

**Comment by seg1129** [comment]
Yes! that would be very helpful. @szh2425 Stephanie can add them to the document.
