### ISSUE TITLE
update the BRP to work with new versions of Chrome and Firefox

### ISSUE THREAD

**Issue by seg1129** [chop-dbhi/biorepo-portal#189]
Currently the React components of the BRP do not work with the new version of Chrome and Firefox.

**Comment by alexfelmeister** [comment]
@seg1129: 

Is this issue all encompassing of the browser update issues? Specifically affecting the subject registration?

Is the issue one that stops people from enrolling subjects?

**Comment by seg1129** [comment]
Yes, in chrome 68 - users were not able to add subjects. The processing bar would just continue to move and behind the scenes the request was failing. For some Chrome 68 was doing something funky with the API request generated by the react component. Here is the fix: #191

**Comment by alexfelmeister** [comment]
Ah cool so that's the thing you fixed. Thanks for clarification @seg1129
