### ISSUE TITLE
Crucial missing redcap records in Fall 2018 Lurie Children's

### ISSUE THREAD

**Issue by alexfelmeister** [chop-dbhi/biorepo-portal#207]
See email from ASF. Contains PHI. 22 external records for patients. Have ehb records and no redcap record.

@seg1129 @alexanderkgonzalez  @alexfelmeister sending email now.

**Comment by alexanderkgonzalez** [comment]
@alexfelmeister problem solved pending redcap dictionary upgrade. Not an inherent issue with the BRP, we can close this.
