### ISSUE TITLE
Django Template Navbar - subjects and record links not working

### ISSUE THREAD

**Issue by seg1129** [chop-dbhi/biorepo-portal#239]
On the record view and record data entry pages the nav bar links for record and subjects do not work. 

**Navbar record link error:**
will return to the subject view page but no external records are showing up. there might be an issue with receiving the protocol number from the URL in the react subject view component. 

**Navbar subjects link error:**
this will return to the project view page with a list of subjects for given protocol, however you are not able to select an individual subject. 

**Django Template Navbar locations:** 
- [individual external record form](https://github.com/chop-dbhi/biorepo-portal/blob/master/dataentry/templates/pds_dataentry_srf.html)
- [external record selection form](https://github.com/chop-dbhi/biorepo-portal/blob/master/dataentry/templates/pds_dataentry_start.html)

**Comment by szh2425** [comment]
oh! oops, sorry about that. 
None of my subjects had records (I forgot to do those steps in the set-up) so I didn't get a chance to test the navbar for the record and record-data entry view. I'll look into this!

**Comment by seg1129** [comment]
No worries! This Navbar is not a react component, it is HTML from the django template so I see this as a separate issue - but I do think the underlying issue is within the subjectView react component. 
Thanks for looking into it!

**Comment by seg1129** [comment]
Record link is now working - there was an issue with the react logic when rendering the detailed subject view page. 

The subject list is still an issue - something is going wrong with the URL when selecting a subject. ... probably more react logic issues.

**Comment by seg1129** [comment]
ok fixed :)
