### ISSUE TITLE
Add same subject to multiple protocols.

### ISSUE THREAD

**Issue by tjrivera** [chop-dbhi/biorepo-portal#60]
Ensure that the portal allows for addition of a subject to a new portal when they already exist on another.

cc: @alexanderkgonzalez

**Comment by alexanderkgonzalez** [comment]
Found temporary manual work around.  Can _manually_ add subject to protocol if already existing in portal.

**Comment by tjrivera** [comment]
@alexanderkgonzalez this should be resolved. Please let me know if you're still encountering issues, otherwise we should be able to close this
