### ISSUE TITLE
Unknown Error on Sample Association despite record being linked

### ISSUE THREAD

**Issue by tjrivera** [chop-dbhi/biorepo-portal#71]
> When a new sample check-in record page is opened, a tech would enter the LIMS ID and click Enter, whereby an "Unknown Error” page opens.  They click the browser’s back button to get to the sample check-in page and then click Enter again, and the sample is successfully linked.
> 
> This has happened with every sample today that both CCCR coordinators have entered

cc: @edward-krause

**Comment by edward-krause** [comment]
@tjrivera One of the CCCR coordinators noticed today that if you double-click on the Save button, the sample is successfully linked on the first try.  Single clicking the Save button still results in the above mentioned error.

**Comment by tjrivera** [comment]
Fixed via 68f7a71
