### ISSUE TITLE
Add Institutional Email field to UserProfile model

### ISSUE THREAD

**Issue by alexanderkgonzalez** [chop-dbhi/biorepo-portal#86]

**Comment by alexanderkgonzalez** [comment]
Could we add (when you get a chance low priority) a model field .....Institutional Email 
Right now we will add email in comments section

**Comment by tjrivera** [comment]
@alexanderkgonzalez this is for use in the initial registration process?

**Comment by seg1129** [comment]
Added to BRP version 1.0.5
